# Generated by Django 4.2.27 on 2025-12-29 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_content", models.TextField(verbose_name="代码内容")),
                ("language", models.CharField(max_length=10, verbose_name="编程语言")),
                ("score", models.FloatField(default=0.0, verbose_name="得分")),
                ("test_count", models.IntegerField(default=0, verbose_name="测试次数")),
                (
                    "total_time",
                    models.FloatField(default=0.0, verbose_name="总耗时（秒）"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "提交",
                "verbose_name_plural": "提交",
                "db_table": "submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_content", models.TextField(verbose_name="代码内容")),
                ("language", models.CharField(max_length=10, verbose_name="编程语言")),
                (
                    "test_results",
                    models.JSONField(default=dict, verbose_name="测试结果"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="测试时间"),
                ),
            ],
            options={
                "verbose_name": "测试尝试",
                "verbose_name_plural": "测试尝试",
                "db_table": "test_attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="是否通过")),
                (
                    "output",
                    models.TextField(blank=True, null=True, verbose_name="输出"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "execution_time",
                    models.FloatField(default=0.0, verbose_name="执行时间（秒）"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="submissions.submission",
                        verbose_name="提交",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试结果",
                "verbose_name_plural": "测试结果",
                "db_table": "test_results",
            },
        ),
    ]
