# Generated by Django 4.2.27 on 2025-12-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="function_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="函数名称"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="solution_mode",
            field=models.CharField(
                choices=[("full", "完整程序"), ("function", "函数模式")],
                default="full",
                max_length=20,
                verbose_name="代码模式",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="template_code",
            field=models.TextField(blank=True, null=True, verbose_name="模板代码"),
        ),
    ]
