# Generated by Django 4.2.27 on 2025-12-29 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="班级名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="班级描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "班级",
                "verbose_name_plural": "班级",
                "db_table": "classes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvitationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="邀请码"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(
                        default=0, verbose_name="最大使用次数（0表示无限制）"
                    ),
                ),
                (
                    "current_uses",
                    models.IntegerField(default=0, verbose_name="当前使用次数"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_codes",
                        to="classes.class",
                        verbose_name="班级",
                    ),
                ),
            ],
            options={
                "verbose_name": "邀请码",
                "verbose_name_plural": "邀请码",
                "db_table": "invitation_codes",
            },
        ),
    ]
