# Generated by Django 4.2.27 on 2025-12-29 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="joined_classes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="学生",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_classes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建教师",
            ),
        ),
    ]
